id: eb8a9c1c-f532-4630-817c-1ecd8a60ed80
name: Cross-tenant Access Settings Organization Deleted
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationDeleted.yaml'
version: 1.0.1
kind: Scheduled
