id: 6706351c-cd6d-4410-931f-eb3c9a63ea9f
name: Cross-tenant Access Settings Organization Added
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationAdded.yaml'
version: 1.0.1
kind: Scheduled
