id: 276d5190-38de-4eb2-9933-b3b72f4a5737
name: Cross-tenant Access Settings Organization Inbound Direct Settings Changed
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationInboundDirectSettingsChanged.yaml'
version: 1.0.1
kind: Scheduled
