id: 394fbb60-6bbe-4870-aa21-7f1171e0230b
name: Cross-tenant Access Settings Organization Outbound Collaboration Settings Changed
description: |
  'As part of content migration, this file is moved to a new location. You can find it here https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/Azure%20Active%20Directory/Analytic%20Rules/Cross-tenantAccessSettingsOrganizationOutboundCollaborationSettingsChanged.yaml'
version: 1.0.1
kind: Scheduled
