id: b31e3072-623a-40f4-8086-240f701108d5
name: (Preview) GitHub - Oauth application - a client secret was removed
description: |
  'As part of content migration, this file is moved to new location. you can find here: https://github.com/Azure/Azure-Sentinel/blob/master/Solutions/GitHub'