id: 2de5308c-aab6-4eaf-8c1c-cf9ad251057e
name: (Private Preview) CMMC Configuration Management Control Family Monitoring
description: |
  'CMMC Control Assessments have Deviated from Configured Threshold Baselines'
severity: Medium
requiredDataConnectors:
  - connectorId: AzureSecurityCenter
    dataTypes:
      - SecurityAlert (ASC)
queryFrequency: 7d
queryPeriod: 7d
triggerOperator: gt
triggerThreshold: 0
tactics:
  - Discovery
relevantTechniques:
  - T1082
query: |

let Policymap = datatable(RecommendationName:string, ControlFamily:string, ControlNumber:string, MaturityLevel:string, 800171Map:string, 80053Map:string)
[
'Adaptive application controls for defining safe applications should be enabled on your machines',	'Configuration Management',	'CM.2.061',	'ML-2',	'3.4.1',	'CM-2, CM-6, CM-8, CM-8(1)',
'An activity log alert should exist for specific Policy operations',	'Configuration Management',	'CM.2.061',	'ML-2',	'3.4.1',	'CM-2, CM-6, CM-8, CM-8(1)',
'Role-Based Access Control should be used on Kubernetes Services',	'Configuration Management',	'CM.2.062',	'ML-2',	'3.4.6',	'CM-7',
'Adaptive application controls for defining safe applications should be enabled on your machines',	'Configuration Management',	'CM.2.063',	'ML-2',	'3.4.9',	'CM-11',
'Allowlist rules in your adaptive application control policy should be updated',	'Configuration Management',	'CM.2.063',	'ML-2',	'3.4.9',	'CM-11',
'Security Center standard pricing tier should be selected',	'Configuration Management',	'CM.2.063',	'ML-2',	'3.4.9',	'CM-11',
'Firewall should be enabled on Key Vault',	'Configuration Management',	'CM.2.064',	'ML-2',	'3.4.2',	'CM-2, CM-6,CM-8,CM-8(1)',
'All network ports should be restricted on network security groups associated to your virtual machine',	'Configuration Management',	'CM.2.064',	'ML-2',	'3.4.2',	'CM-2, CM-6,CM-8,CM-8(1)',
'Virtual networks should be protected by Azure Firewall',	'Configuration Management',	'CM.2.064',	'ML-2',	'3.4.2',	'CM-2, CM-6,CM-8,CM-8(1)',
'Web Application Firewall (WAF) should use the specified mode for Azure Front Door Service',	'Configuration Management',	'CM.2.064',	'ML-2',	'3.4.2',	'CM-2, CM-6,CM-8,CM-8(1)',
'An activity log alert should exist for Delete SQL Server Firewall Rule',	'Configuration Management',	'CM.2.065',	'ML-2',	'3.4.3',	'CM-3',
'An activity log alert should exist for the Delete Network Security Group Rule',	'Configuration Management',	'CM.2.065',	'ML-2',	'3.4.3',	'CM-3',
'An activity log alert should exist for Delete Network Security Solution',	'Configuration Management',	'CM.2.065',	'ML-2',	'3.4.3',	'CM-3',
'Azure Monitor should collect activity logs from all regions',	'Configuration Management',	'CM.2.065',	'ML-2',	'3.4.3',	'CM-3',
'Access to storage accounts with firewall and virtual network configurations should be restricted',	'Configuration Management',	'CM.3.068',	'ML-3',	'3.4.7',	'CM-7(1), CM-7(2)',
'Storage account public access should be disallowed',	'Configuration Management',	'CM.3.068',	'ML-3',	'3.4.7',	'CM-7(1), CM-7(2)',
'Non-internet-facing virtual machines should be protected with network security groups',	'Configuration Management',	'CM.3.068',	'ML-3',	'3.4.7',	'CM-7(1), CM-7(2)',
'Subnets should be associated with a network security group',	'Configuration Management',	'CM.3.068',	'ML-3',	'3.4.7',	'CM-7(1), CM-7(2)',
'Adaptive application controls for defining safe applications should be enabled on your machines',	'Configuration Management',	'CM.3.068',	'ML-3',	'3.4.7',	'CM-7(1), CM-7(2)',
'Adaptive application controls for defining safe applications should be enabled on your machines',	'Configuration Management',	'CM.3.069',	'ML-3',	'3.4.8',	'CM-7(4), CM-7(5)'
];
SecurityRecommendation
| join kind=rightouter Policymap on RecommendationName
| where ControlFamily == 'System & Information Integrity'
| summarize
    Assessments = count(),
    Success = countif(RecommendationState == 'Healthy' or RecommendationState == 'NotApplicable'),
    Failed = countif(RecommendationState == 'Unhealthy')
    by ControlFamily, ControlNumber, MaturityLevel, RecommendationName, AssessedResourceId
| extend SuccessRatePercentage = (Success * 100 / Assessments)
| extend FailedRatePercentage = (Failed * 100 / Assessments)
| project
    ControlNumber,
    ControlFamily,
    MaturityLevel,
    RecommendationName,
    Assessments,
    SuccessRatePercentage,
    FailedRatePercentage,
    AssessedResourceId
| where RecommendationName <> ''
// | where RecommendationName <> '' //Filter Out or Suppress Recommendations
// | where MaturityLevel == 'ML-3' //Filter by Maturity Level 
| where FailedRatePercentage > 30 //Adjust Either FailedRatePercentage or PasedRatePercentage Thresholds within Organizational Needs
| sort by FailedRatePercentage desc
| limit 250
| extend HostCustomEntity = AssessedResourceId

entityMappings:
  - entityType: Host
    fieldMappings:
      - identifier: FullName
        columnName: HostCustomEntity
version: 1.0.0
