id: 0faffbdf-4f9e-43f9-a7c0-25c84bc68736
name: Cross-tenant Access Settings Organization Deleted
description: |
  'Organizations are added in the Cross-tenant Access Settings to control communication inbound or outbound for users and applications. This detection notifies when an Organization is deleted from the Azure AD Cross-tenant Access Settings.'
severity: Medium
requiredDataConnectors:
  - connectorId: AzureActiveDirectory
    dataTypes:
      - AuditLogs
queryFrequency: 2d
queryPeriod: 2d
triggerOperator: gt
triggerThreshold: 0
status: Available
tactics:
  - InitialAccess
  - Persistence
  - Discovery
relevantTechniques:
  - T1078.004
  - T1136.003
  - T1087.004
query: |
  AuditLogs
  | where OperationName has "Delete partner specific cross-tenant access setting"
  | extend InitiatedByActionUserInformation = iff(isnotempty(InitiatedBy.user.userPrincipalName), InitiatedBy.user.userPrincipalName, InitiatedBy.app.displayName)
  | extend InitiatedByIPAdress = InitiatedBy.user.ipAddress
  | extend ExtTenantDeleted = TargetResources[0].modifiedProperties[0].oldValue
entityMappings:
  - entityType: Account
    fieldMappings:
      - identifier: FullName
        columnName: ExtTenantDeleted
  - entityType: Account
    fieldMappings:
      - identifier: Name
        columnName: InitiatedByActionUserInformation
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: InitiatedByIPAdress
version: 1.0.0
kind: Scheduled
