id: ff0af873-a2f2-4233-8412-0ef4e00b0156
name: 'Dynatrace Application Security - Non-critical Security Problem detection'
description: 'Detect vulnerabilities in your environment at runtime insights by snyk'
severity: Informational
status: Available
requiredDataConnectors:
  - connectorId: DynatraceVulnerabilities
    dataTypes:
      - DynatraceSecurityProblems_CL
queryFrequency: P1D
queryPeriod: P1D
triggerOperator: GreaterThan
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
eventGroupingSettings:
  aggregationKind: AlertPerResult
query: |
  DynatraceSecurityProblems_CL
  | where riskAssessment_riskLevel_s != "CRITICAL"
  | summarize  arg_max(lastUpdatedTimestamp_d, *) by securityProblemId_s
alertDetailsOverride:
  alertDisplayNameFormat: 'Dynatrace Code-Level vulnerability detected - {{displayId_s}} : {{title_s}}'
  alertDescriptionFormat: Code-Level vulnerability ({{externalVulnerabilityId_s}}) detected in package ({{packageName_s}}), more details available from Dynatrace at {{url_s}}.
  alertSeverityColumnName: riskAssessment_riskLevel_s
customDetails:
  securityProblemId: securityProblemId_s
  displayId: displayId_s
  securityProblemUrl: url_s
  riskLevel: riskAssessment_riskLevel_s
  packageName: packageName_s
  technology: technology_s
  vulnerabilityType: vulnerabilityType_s
  cveIds: cveIds_s
  externVulnId: externalVulnerabilityId_s
  riskScore: riskAssessment_baseRiskScore_d
  riskVector: riskAssessment_baseRiskVector_s
  exposure: riskAssessment_exposure_s
  publicExploit: riskAssessment_publicExploit_s
  dataAssets: riskAssessment_dataAssets_s
  vulnerableFuncUsage: riskAssessment_vulnerableFunctionUsage_s
incidentConfiguration:
  createIncident: false
  groupingConfiguration:
    enabled: true
    reopenClosedIncident: true
    lookbackDuration: P7D
    matchingMethod: Selected
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails:
      - securityProblemId
version: 1.0.0
kind: Scheduled
