id: ff0af873-a2f2-4233-8412-0ef4e00b0156
name: Dynatrace Application Security - Non-critical vulnerability detection
description: Detect vulnerabilities in your environment at runtime insights by snyk
severity: Informational
status: Available
requiredDataConnectors:
  - connectorId: DynatraceVulnerabilities
    dataTypes:
      - DynatraceSecurityProblems_CL
queryFrequency: 1d
queryPeriod: 1d
triggerOperator: gt
triggerThreshold: 0
suppressionDuration: 5h
suppressionEnabled: false
tactics:
  - DefenseEvasion
  - Execution
  - Impact
  - InitialAccess
  - LateralMovement
  - Persistence
  - PrivilegeEscalation
relevantTechniques: # none
eventGroupingSettings:
  aggregationKind: SingleAlert
query: |
  DynatraceSecurityProblems
  | where DAVISRiskLevel != "CRITICAL"
  | summarize  arg_max(LastUpdatedTimeStamp, *) by SecurityProblemId
entityMappings: # none
alertDetailsOverride:
  alertDisplayNameFormat: 'Dynatrace Non-critical vulnerability detected - {{DisplayId}} : {{Title}}'
  alertDescriptionFormat: |
    Non-critical vulnerability ({{ExternalVulnerabilityId}}) detected in package ({{PackageName}}), more details available from Dynatrace at {{Url}}.
  alertTacticsColumnName: # none
  alertSeverityColumnName: Severity
customDetails:
  SecurityProblemId: SecurityProblemId
  DisplayId: DisplayId
  SecurityProblemUrl: Url
  DAVISRiskLevel: DAVISRiskLevel
  PackageName: PackageName
  Technology: Technology
  VulnerabilityType: VulnerabilityType
  CVEIds: CVEIds
  ExternalVulnId: externalVulnerabilityId
  DAVISRiskScore: DAVISRiskScore
  DAVISRiskVector: DAVISRiskVector
  DAVISExposure: DAVISExposure
  DAVISPublicExploit: DAVISPublicExploit
  DAVISDataAssets: DAVISDataAssets
  DAVISVulnFuncUsage: DAVISVulnerableFuncUsage
incidentConfiguration:
  createIncident: false
  groupingConfiguration:
    enabled: true
    reopenClosedIncident: true
    lookbackDuration: 7d
    matchingMethod: Selected
    groupByEntities: []
    groupByAlertDetails: []
    groupByCustomDetails:
      - SecurityProblemId
version: 1.0.0
kind: Scheduled
