id: 305093b4-0fa2-57bc-bced-caea782a6e9c
name: Dynatrace Application Security - Code-Level vulnerability detection
description: Detect Code-level vulnerabilities in your environment at runtime insights by snyk
severity: Medium
status: Available
requiredDataConnectors:
  - connectorId: DynatraceVulnerabilities
    dataTypes:
      - DynatraceSecurityProblems_CL
queryFrequency: 1d
queryPeriod: 1d
triggerOperator: gt
triggerThreshold: 0
suppressionDuration: 5h
suppressionEnabled: false
tactics:
  - DefenseEvasion
  - Execution
  - Impact
  - InitialAccess
  - LateralMovement
  - Persistence
  - PrivilegeEscalation
eventGroupingSettings:
  aggregationKind: SingleAlert
query: |
  DynatraceSecurityProblems
  | where VulnerabilityType == "CODE_LEVEL" and DAVISRiskLevel == "CRITICAL"
  | summarize  arg_max(LastUpdatedTimeStamp, *) by SecurityProblemId
alertDetailsOverride:
  alertDisplayNameFormat: 'Dynatrace Code-Level vulnerability detected - {{DisplayId}} : {{Title}}'
  alertDescriptionFormat: | 
    Code-Level vulnerability ({{ExternalVulnerabilityId}}) detected in package ({{PackageName}}), more details available from Dynatrace at {{Url}}.
  alertSeverityColumnName: Severity
customDetails:
  SecurityProblemId: SecurityProblemId
  DisplayId: DisplayId
  SecurityProblemUrl: Url
  DAVISRiskLevel: DAVISRiskLevel
  PackageName: PackageName
  Technology: Technology
  VulnerabilityType: VulnerabilityType
  CVEIds: CVEIds
  ExternalVulnId: externalVulnerabilityId
  DAVISRiskScore: DAVISRiskScore
  DAVISRiskVector: DAVISRiskVector
  DAVISExposure: DAVISExposure
  DAVISPublicExploit: DAVISPublicExploit
  DAVISDataAssets: DAVISDataAssets
  DAVISVulnFuncUsage: DAVISVulnerableFuncUsage
incidentConfiguration:
  createIncident: false
  groupingConfiguration:
    enabled: true
    reopenClosedIncident: true
    lookbackDuration: 7d
    matchingMethod: Selected
    groupByEntities:
    groupByAlertDetails: []
    groupByCustomDetails:
      - SecurityProblemId
version: 1.0.0
kind: Scheduled
