id: 1b0b2065-8bac-5a00-83c4-1b58f69ac212
name: Dynatrace Application Security - Attack detection
description: |
  Dynatrace has detected an ongoing attack in your environment.
severity: High
status: Available
requiredDataConnectors:
  - connectorId: DynatraceAttacks
    dataTypes:
      - DynatraceAttacks_CL
queryFrequency: 1d
queryPeriod: 1d
triggerOperator: gt
triggerThreshold: 0
suppressionDuration: 5h
suppressionEnabled: false
tactics:
  - Execution
  - Impact
  - InitialAccess
  - PrivilegeEscalation
relevantTechniques:
  - T1059
  - T1565
  - T1190
  - T1068
eventGroupingSettings:
  aggregationKind: AlertPerResult
query: |
  DynatraceAttacks
  | summarize  arg_max(TimeStamp, *) by AttackId
entityMappings: # none
alertDetailsOverride:
  alertDisplayNameFormat: 'Dynatrace Attack detected - {{DisplayId}} : {{DisplayName}}'
  alertDescriptionFormat: |
    Dynatrace has detected an ongoing attack in your environment.
  alertTacticsColumnName: # none
  alertSeverityColumnName: # none 
customDetails:
  AttackId: AttackId
  AttackType: AttackType
  AttackState: State
  AttackDisplayId: DisplayId
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: true
    reopenClosedIncident: true
    lookbackDuration: 7d
    matchingMethod: Selected
    groupByEntities:
    groupByAlertDetails: []
    groupByCustomDetails:
      - AttackId
version: 1.0.0
kind: Scheduled
