id: 1b0b2065-8bac-5a00-83c4-1b58f69ac212
name: 'Dynatrace Application Security - Attack detection'
description: |
  'Dynatrace has detected an ongoing attack in your environment.'
severity: High
status: Available
requiredDataConnectors:
  - connectorId: DynatraceAttacks
    dataTypes:
      - DynatraceAttacks
queryFrequency: P1D
queryPeriod: P1D
triggerOperator: GreaterThan
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
tactics:
  - Execution
  - Impact
  - InitialAccess
  - PrivilegeEscalation
techniques:
  - T1059
  - T1565
  - T1190
  - T1068
eventGroupingSettings:
  aggregationKind: AlertPerResult
query: |
  DynatraceAttacks
  | summarize  arg_max(TimeStamp, *) by AttackId
alertDetailsOverride:
  alertDisplayNameFormat: 'Dynatrace Attack detected - {{DisplayId}} : {{DisplayName}}'
  alertDescriptionFormat: Dynatrace has detected an ongoing attack in your environment.
customDetails:
  AttackId: AttackId
  AttackType: AttackType
  AttackState: State
  AttackDisplayId: DisplayId
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: true
    reopenClosedIncident: true
    lookbackDuration: P7D
    matchingMethod: Selected
    groupByEntities:
    groupByAlertDetails: []
    groupByCustomDetails:
      - AttackId
version: 1.0.0
kind: Scheduled
