id: 415978ff-074e-4203-824a-b06153d77bf7
name: 'Dynatrace - Observability Problem Detected'
description: |
  'Detect Observability issues in your environment'
severity: Informational
status: Available
requiredDataConnectors:
  - connectorId: DynatraceProblems
    dataTypes:
      - DynatraceProblems_CL
queryFrequency: P1D
queryPeriod: P1D
triggerOperator: GreaterThan
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
eventGroupingSettings:
  aggregationKind: AlertPerResult
query: |
  DynatraceProblems_CL
  | summarize  arg_max(startTime_d, *) by problemId_s
alertDetailsOverride:
  alertDisplayNameFormat: 'Dynatrace problem detected - {{displayId_s}} : {{title_s}}'
  alertDescriptionFormat: A Performance and/or Availability issue has been detected in your environment
  alertSeverityColumnName: severityLevel_s
customDetails:
  problemId: problemId_s
  displayId: displayId_s
  impactLevel: impactLevel_s
  severityLevel: severityLevel_s
version: 1.0.0
kind: Scheduled
