id: 1b0b2065-8bac-5a00-83c4-1b58f69ac212
name: 'Dynatrace Application Security - Attack detected'
description: |
  'Dynatrace has detected an ongoing Attack in your environment.'
severity: High
status: Available
requiredDataConnectors:
  - connectorId: DynatraceAttacks
    dataTypes:
      - DynatraceAttacks_CL
queryFrequency: P1D
queryPeriod: P1D
triggerOperator: GreaterThan
triggerThreshold: 0
suppressionDuration: PT5H
suppressionEnabled: false
tactics:
  - InitialAccess
eventGroupingSettings:
  aggregationKind: AlertPerResult
query: |
  DynatraceAttacks_CL
  | summarize  arg_max(timestamp_d, *) by attackId_s
alertDetailsOverride:
  alertDisplayNameFormat: 'Dynatrace Attack detected - {{displayId_s}} : {{displayName_s}}'
  alertDescriptionFormat: Dynatrace has detected an ongoing Attack in your environment.
customDetails:
  attackId: attackId_s
  attackType: attackType_s
  state: state_s
  displayId: displayId_s
incidentConfiguration:
  createIncident: true
  groupingConfiguration:
    enabled: true
    reopenClosedIncident: true
    lookbackDuration: P7D
    matchingMethod: Selected
    groupByEntities:
    groupByAlertDetails: []
    groupByCustomDetails:
      - attackId
version: 1.0.0
kind: Scheduled
