id: ca9839c6-8a6e-4a67-a11d-daef0b1eb7a4
Function:
  Title: Parser for ExchangeEnvironmentList
  Version: '1.0.0'
  LastUpdated: '2023-08-08'
Category: Microsoft Sentinel Parser
FunctionName: ExchangeEnvironmentList
FunctionAlias: ExchangeEnvironmentList
FunctionQuery: |
    let _target = iff(isnull(Target) or isempty(Target),"On-Premises",Target);
    let ScalarbaseRequest = union isfuzzy=true withsource=TableName ESIAPIExchange*,ESIExchange*
        | extend Source = iff (TableName contains "Online", "Online", "On-Premises")
        | where _target == 'All' or Source == _target;
    // Base Request
    ScalarbaseRequest | summarize by ESIEnvironment_s | project-rename ESIEnvironment = ESIEnvironment_s