id: fa6381b3-9033-4c71-90fa-a6af6675783e
name: Crashing Applications
description: |-
  This query identifies crashing processes based on parameters passed
  to werfault.exe and attempts to find the associated process launch
  from DeviceProcessEvents.
requiredDataConnectors:
- connectorId: Microsoft365Defender
  dataTypes:
  - DeviceProcessEvents
tactics:
- Execution
- Misconfiguration
query: |-
  DeviceProcessEvents
  | where Timestamp > ago(1d)
  | where FileName =~ 'werfault.exe'
  | project CrashTime = Timestamp, DeviceId, WerFaultCommand = ProcessCommandLine, CrashProcessId = extract("-p ([0-9]{1,5})", 1, ProcessCommandLine) 
  | join kind= inner hint.strategy=shuffle DeviceProcessEvents on DeviceId
  | where CrashProcessId == ProcessId and Timestamp between (datetime_add('day',-1,CrashTime) .. CrashTime)
  | project-away ActionType
  | project-rename ProcessStartTimestamp = Timestamp
