id: c52ec521-9188-4a9e-a4cd-34a3dfbc3d27
name: IoT/OT Unauthorized Network Configuration - Microsoft Defender for IoT
description: |
  'An unauthorized DHCP configuration on the network can be an indication of a new, unauthorized device operating on the network. This is either a legitimate new device recently deployed on the network or an indication of unauthorized or even malicious activity on the network; a cyber threat attempting to manipulate the SCADA network.'
severity: Medium
requiredDataConnectors:
  - connectorId: IoT
    dataTypes:
      - SecurityAlert (ASC for IoT)
queryFrequency: 6h
queryPeriod: 6h
triggerOperator: gt
triggerThreshold: 0
tactics:
  - Impact
relevantTechniques:
  - T813
query: |
  SecurityAlert
  | where AlertName == "Device Failed to Receive a Dynamic IP Address"
  | where AlertName == "Field Device Discovered Unexpectedly" or AlertName == "New Asset Detected" or AlertName == "Abnormal usage of MAC Addresses" or AlertName == "New LLDP Device Configuration"
  | extend DeviceId = tostring(parse_json(ExtendedProperties).DeviceId)
  | extend IPAddress = tostring(parse_json(tostring(parse_json(Entities)[0].IpAddress)).Address)
  | extend Protocol = tostring(parse_json(tostring(parse_json(Entities)[0].Protocols))[0])
  | extend DeviceType = tostring(parse_json(Entities)[0].DeviceName)
  | extend IoTSecurityAgentId = tostring(parse_json(Entities)[0].IoTSecurityAgentId)
  | extend Vendor = tostring(parse_json(Entities)[0].Vendor)
  | extend RemediationSteps = tostring(parse_json(RemediationSteps)[0])
  | project AlertName, ResourceId, DeviceId, IPAddress, Protocol, DeviceType, Vendor, IoTSecurityAgentId, Tactics, TimeGenerated, RemediationSteps
entityMappings:
  - entityType: IP
    fieldMappings:
      - identifier: Address
        columnName: IPCustomEntity
version: 1.0.0
