id: 945194cc-0bdc-4c63-b465-bd53f09c03da
Function:
  Title: Parser for GitHubDependabotData
  Version: '1.0.0'
  LastUpdated: '2023-08-03'
Category: Microsoft Sentinel Parser
FunctionName: GitHubDependabotData
FunctionAlias: GitHubDependabotData
FunctionParams:
FunctionQuery: |
    githubscanaudit_CL 
    | where action_s in ('create', 'dismiss', 'resolve')
    | extend EventType='RepositoryVulnerabilityAlert'
    | extend alert = todynamic(alert_s),
        organization = todynamic(organization_s),
        repository = todynamic(repository_s),
        sender = todynamic(sender_s) 
    | extend alertcreatedate = alert.created_at, alertaffectedrange = alert.affected_range,   
        alertexternalidentifier= alert.external_identifier,    
        alertghsaid = alert.ghsa_id,
        alertseverity = alert.severity,
        repositoryfullname = repository.full_name,
        repositoryOwnerlogin = repository.owner.login,
        repositoryurl = repository.url,       
        senderlogin = sender.login,
        sendertype = sender.type,
        action=action_s
    | where isnotempty(alertexternalidentifier)
    | project-keep
        TimeGenerated,
        EventType,
        action,
        alertexternalidentifier,
        alertghsaid,
        alertcreatedate,
        repositoryfullname,
        repositoryOwnerlogin,
        repositoryurl,
        senderlogin,
        sendertype