id: 021a4cf9-a5be-48dd-a417-a559f7ccca98
Function:
  Title: Parser for ExchangeEnvironmentList
  Version: '1.0.0'
  LastUpdated: '2023-08-03'
Category: Microsoft Sentinel Parser
FunctionName: ExchangeEnvironmentList
FunctionAlias: ExchangeEnvironmentList
FunctionParams:
FunctionQuery: |
    let _target = iff(isnull(Target) or isempty(Target),"On-Premises",Target);
    let ScalarbaseRequest = union isfuzzy=true withsource=TableName ESIAPIExchange*,ESIExchange*
        | extend Source = iff (TableName contains "Online", "Online", "On-Premises")
        | where _target == 'All' or Source == _target;
    // Base Request
    ScalarbaseRequest | summarize by ESIEnvironment_s | project-rename ESIEnvironment = ESIEnvironment_s