 
id: 0b85a077-8ba5-4cb5-90f7-1e882afe10c5
name: (Preview) GitHub - Oauth application - a client secret was removed
severity: Medium
requiredDataConnectors: []
queryFrequency: 1d
queryPeriod: 7d
triggerOperator: gt
triggerThreshold: 0
tactics:
  - InitialAccess
relevantTechniques:
  - T1078
query: |
GitHubAuditLogPolling_CL | 
where action_s == "oauth_application.remove_client_secret"
version: 1.0.0
kind: Scheduled