jobs:
- job: "HyperLinkValidations"
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: 'npm install -g npm@8.19.2;which npm;npm -v'
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false
      command: 'install'
  - script: 'npm run tsc && node .script/hyperLinkValidator.js'
    displayName: 'Hyper Link Validations'
