jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
  steps:
    - bash: |
        echo "$(which git)"
      env:
        git: $(which git)
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - script: |
        $commitId=$(Build.SourceVersion)
        $modifiedFiles=$(git diff --name-only HEAD~1 HEAD)
        dotnet test '**/Kqlvalidations.Tests.csproj' --configuration $(buildConfiguration) --filter ModifiedFiles=@$(modifiedFiles)
      displayName: 'Run kql validation tests'
      condition: eq(variables['Build.Reason'], 'PullRequest')





