jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '3.1.401'
    buildPlatform: 'Any CPU'
    FOO: $(System.PullRequest.PullRequestNumber)
    
  steps:
    - bash: |
        echo "$FOO"
      env:
        FOO: $(FOO)
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'