jobs:
- job: "KqlValidations"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '6.0.x'
    PRNum: $(System.PullRequest.PullRequestNumber)
  steps:
    - bash: |
        echo "$PRNum"
      env:
        FOO: $(PRNumber)
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
      inputs:
        packageType: 'sdk'
        version: '$(dotnetSdkVersion)'
    - task: DotNetCoreCLI@2
      displayName: 'Run kql validation tests'
      inputs:
        command: 'test'
        arguments: '--configuration $(buildConfiguration)'
        publishTestResults: true
        projects: '**/Kqlvalidations.Tests.csproj'