jobs:
  - job: "sampleDataValidator"
    pool:
      vmImage: "ubuntu-18.04"
    steps:
      - task: Npm@1
        displayName: "npm install"
        inputs:
          verbose: false
          command: "install --registry https://registry.npmjs.org"
      - script: "npm run tsc && node .script/sampleDataValidator.js"
        displayName: "sample Data Validator"
