  
name: run script on changing detections
on:
  pull_request:
    paths:
       - 'Detection**'
      
jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - uses: mshick/add-pr-comment@v1
        env:
          APPTOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          message: |
            **Hello how are you I am GitHub bot**
            😀😀
            I see that you changed templates under the detections folder. Did you remember to update the version of the templates you changed?
            If not, and if you want customers to be aware that a new version of this template is available, please update the ``version`` property of the template you changed.
          repo-token: ${{ env.APPTOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
