name: Add Comment on Packaged PR on Merge

on:
  pull_request:
    branches:
      - master
    paths:
      - Solutions/**
    types: [closed]

jobs:
  if_merged:
    if: ${{ github.event.pull_request.merged && !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
    - name: Generate a token
      id: generate_token
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      with:
        app_id: ${{ secrets.APPLICATION_ID }}
        private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

    - uses: actions/github-script@29423367f079522048aa7c63f671593b0556ffd5
      id: addComment
      env:
        APPTOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        github-token: ${{ env.APPTOKEN }}
        script: |
          const childPRDescription = context.payload.pull_request.body
          if (childPRDescription != null && childPRDescription.includes('Automation have successfully generated package'))
          {
            // Add comment on packaged PR i.e. child PR
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "The solution package has now been merged into master. To make this package available on the Microsoft Sentinel Content hub, review the publishing guidance [here](https://github.com/Azure/Azure-Sentinel/tree/master/Solutions#step-3--publish-your-solution)"
            })
          }
          else
          {
            console.log('Skipping addition of comment as PR is not an auto generated PR!')
          }
