name: Add Label on Pull Request

on:  
  workflow_call:
    inputs:
      labelName:
        required: true
        type: string

jobs:
  addLabelOnPR:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - uses: actions/github-script@29423367f079522048aa7c63f671593b0556ffd5
        name: Add Label To Pull Request
        env:
          LABEL_NAME: ${{ inputs.labelName }}
          APPTOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          github-token: ${{ env.APPTOKEN }}
          script: |
            $labelName = "${{ env.LABEL_NAME }}"
            github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [$labelName]
            })