# ADD P0 LABEL IF THE PULL REQUEST IS FROM EXTERNAL PUBLISHER I.E ISV'S
name: "Pull Request Labeler"

on:  
  pull_request:
    branches:
      - master
    paths:
      - Solutions/**

jobs:
  solutionNameDetails:
    permissions:
      contents: read
      pull-requests: read
    if: ${{ github.actor != 'dependabot[bot]' && !github.event.pull_request.head.repo.fork && !contains(github.event.pull_request.labels.*.name, 'P0')}}
    uses: ./.github/workflows/getSolutionName.yaml
    secrets: inherit

  solutionPublisherDetail:
    needs: solutionNameDetails
    permissions:
      contents: read
      pull-requests: read
    if: ${{ github.actor != 'dependabot[bot]' && needs.solutionNameDetails.outputs.solutionName != '' && !github.event.pull_request.head.repo.fork }}
    uses: ./.github/workflows/neworexistingsolution.yaml
    with: 
      solutionName: "${{ needs.solutionNameDetails.outputs.solutionName }}"
    secrets: inherit

  Labeler:
    runs-on: ubuntu-latest
    needs: solutionPublisherDetail
    permissions:
      contents: write
      pull-requests: write
    if: ${{ github.actor != 'dependabot[bot]' && needs.solutionPublisherDetail.outputs.solutionPublisherId != '' && !contains(fromJson(vars.INTERNAL_PUBLISHERS),needs.solutionPublisherDetail.outputs.solutionPublisherId) }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Add Label Notification
        uses: actions/github-script@v6
        env:
          APPTOKEN: ${{ steps.generate_token.outputs.token }}
        with:
          github-token: ${{ env.APPTOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['P0']
            })
            
