name: Arm-ttk Validations

on: [pull_request]

jobs:
  run-arm-ttk:
    runs-on: ubuntu-latest
    outputs:
      solutionName: ${{ steps.step1.outputs.solutionName }}
      mainTemplateChanged: ${{ steps.step1.outputs.mainTemplateChanged }}
      createUiChanged: ${{ steps.step1.outputs.createUiChanged }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - shell: pwsh
        id: step1
        name: Identify Changes in PR
        run: | 
          $diff = git diff --diff-filter=d --name-only HEAD^ HEAD
          Write-Host "List of files in PR: $diff"
          
          $hasmainTemplateChanged = $false
          $hasCreateUiDefinitionTemplateChanged = $false

          $requiredFiles = @("mainTemplate.json", "createUiDefinition.json")
          $filesList = $diff | Where-Object {$_ -match ($requiredFiles -Join "|")}

          if ($filesList.Count > 0)
          {
            if ($filesList -Contains "mainTemplate.json")
            {
              $hasmainTemplateChanged = $true
            }

            if ($filesList -Contains "createUiDefinition.json")
            {
              $hasCreateUiDefinitionTemplateChanged = $true
            }

            $fileValue = $filesList[0]
            $solutionIndex = $fileValue.IndexOf("Solutions/")
            $solutionNameWithOtherPath = $fileValue.SubString($solutionIndex + 10)
            if ($solutionNameWithOtherPath -ne '' -and $solutionNameWithOtherPath -ne $null)
            {
              $headers = $solutionNameWithOtherPath -split '/', 3
              if ($null -ne $headers[0])
              {
                $sName = $headers[0]
              }
            }

            Write-Output "::set-output name=solutionName::$sName"
            Write-Output "::set-output name=mainTemplateChanged::$hasmainTemplateChanged"
            Write-Output "::set-output name=createUiChanged::$hasCreateUiDefinitionTemplateChanged"
          }

      - uses: docker/build-push-action@v2
        id: publishGithubPackage
        name: Run ARM-TTK
        if: ${{ success() && steps.step1.outcome == 'success' && steps.step1.outputs.solutionName != '' && (steps.step1.outputs.mainTemplateChanged == 'true' || steps.step1.outputs.createUiChanged == 'true') }}
        env: 
          SolutionName: ${{ steps.step1.outputs.solutionName }}
          mainTemplateChanged: ${{ steps.step1.outputs.mainTemplateChanged }}
          createUiChanged: ${{ steps.step1.outputs.createUiChanged }}
        with:
          context: .
          file: ./.github/actions/Dockerfile
          push: false
          build-args: |
            SolutionName
            mainTemplateChanged
            createUiChanged
