name: Arm-ttk Validations

on: [pull_request]

jobs:
  run-arm-ttk:
    runs-on: ubuntu-latest
    outputs:
      solutionName: ${{ steps.step1.outputs.solutionName }}
      mainTemplateChanged: ${{ steps.step1.outputs.mainTemplateChanged }}
      createUiChanged: ${{ steps.step1.outputs.createUiChanged }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - shell: pwsh
        id: step1
        name: Identify Changes in PR
        run: |
          $diff = git diff --diff-filter=d --name-only HEAD^ HEAD
          Write-Host "List of files in PR: $diff"
          
          $hasmainTemplateChanged = $false
          $hasCreateUiDefinitionTemplateChanged = $false

          $SourceDiff = $diff | ForEach-Object {
            $currentFile = Get-ChildItem -Path $_ -File
            if ($currentFile)
            {
              $currentFileStr = $currentFile.ToString()
              $mainTemplateChanged = $currentFileStr.ToLower().Contains("maintemplate.json")
              $createUiDefinitionTemplateChanged = $currentFileStr.ToLower().Contains("createuidefinition.json")

              if ($mainTemplateChanged -eq $true)
              {
                $hasmainTemplateChanged = $true
              }

              if ($createUiDefinitionTemplateChanged -eq $true)
              {
                $hasCreateUiDefinitionTemplateChanged = $true
              }

              $fileValue = (($currentFile.DirectoryName).Split("\")[-1])
              $solutionIndex = $fileValue.IndexOf("Solutions/")
              if ($solutionIndex -gt -1 -and $null -ne $solutionIndex  -and $solutionName -ne '')
              {
                $solutionNameWithOtherPath = $fileValue.SubString($solutionIndex + 10)
                if ($solutionNameWithOtherPath -ne '' -and $solutionNameWithOtherPath -ne $null)
                {
                  $headers = $solutionNameWithOtherPath -split '/', 3
                  if ($null -ne $headers[0])
                  {
                    $sName = $headers[0]
                  }
                }
              }
            }

          Write-Output "::set-output name=solutionName::$sName"
          Write-Output "::set-output name=mainTemplateChanged::$hasmainTemplateChanged"
          Write-Output "::set-output name=createUiChanged::$hasCreateUiDefinitionTemplateChanged"

      - uses: docker/build-push-action@v2
        id: publishGithubPackage
        name: Run ARM-TTK
        if: ${{ success() && steps.step1.outcome == 'success' && steps.step1.outputs.solutionName != '' && (steps.step1.outputs.mainTemplateChanged == 'true' || steps.step1.outputs.createUiChanged == 'true') }}
        env: 
          SolutionName: ${{ steps.step1.outputs.solutionName }}
          mainTemplateChanged: ${{ steps.step1.outputs.mainTemplateChanged }}
          createUiChanged: ${{ steps.step1.outputs.createUiChanged }}
        with:
          context: .
          file: ./.github/actions/Dockerfile
          push: false
          build-args: |
            SolutionName
            mainTemplateChanged
            createUiChanged
