# IF createPackage ATTRIBUTE IN DATA INPUT FILE IS SPECIFIED AS FALSE THEN SKIP PACKAGE CREATION ELSE DEFAULT IS CREATE PACKAGE
name: Check if packaging need to be Skipped

on:
  workflow_call:
    inputs:
      solutionName:
        required: true
        type: string
    outputs:
      isPackagingRequired:
        description: "Solution name for the current pr"
        value: ${{ jobs.checkPackagingInfoStatus.outputs.isPackagingRequired }}

env:
  BRANCH_NAME: ${{ github.event.client_payload.pull_request.head.ref && github.event.client_payload.pull_request.head.ref || github.event.client_payload.pullRequestBranchName }}

jobs:
  checkPackagingInfoStatus:
    name: Check If Packaging Need to skip
    runs-on: ubuntu-latest
    outputs:
      isPackagingRequired: ${{ steps.getPackagingSkipStatus.outputs.isPackagingRequired }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        env:
          GeneratedToken: ${{ steps.generate_token.outputs.token }}
        with:
          fetch-depth: 2
          ref: "${{ env.BRANCH_NAME }}"
          token: ${{ env.GeneratedToken}}
      - name: Check Skip Packaging Status
        shell: pwsh
        id: getPackagingSkipStatus
        run: |
          $instrumentationKey = "${{ vars.APPINSIGHTS }}"
          $runId = "${{ github.run_id }}"
          $solutionName = "${{ inputs.solutionName }}"
          $baseFolderPath = "/home/runner/work/Azure-Sentinel/Azure-Sentinel/"
          $pullRequestNumber = "${{ github.event.client_payload.pull_request.number && github.event.client_payload.pull_request.number || github.event.client_payload.pullRequestNumber }}"
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml
          ./.script/package-automation/checkSkipPackagingInfo.ps1 $solutionName $pullRequestNumber $runId $baseFolderPath $instrumentationKey
