name: Check if Automated Pull Request

on:
  workflow_call:
    outputs:
      isAutomatedPR:
        description: "Is Automated PR"
        value: ${{ jobs.checkAutomatedPR.outputs.isAutomatedPR }}

permissions:
  contents: read
  pull-requests: read

env:
  BRANCH_NAME: ${{ github.event.client_payload.pull_request.head.ref && github.event.client_payload.pull_request.head.ref || github.event.client_payload.pullRequestBranchName }}
  BODY: ${{ github.event.issue.body }}

jobs:
  checkAutomatedPR:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    outputs:
      isAutomatedPR: ${{ steps.ValidateAutomatedPR.outputs.isAutomatedPR }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APPLICATION_ID }}
          private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        env:
          GeneratedToken: ${{ steps.generate_token.outputs.token }}
        with:
          fetch-depth: 2
          ref: "${{ env.BRANCH_NAME }}"
          token: ${{ env.GeneratedToken}}
      - shell: pwsh
        id: ValidateAutomatedPR
        run: |
          $prBodyContent = "${{ env.BODY }}"
          $isAutomatedPR = $false
          if ($prBodyContent -like '*Automation have successfully*')
          {
            Write-Host "This Pull Request is autogenerated!"
            $isAutomatedPR = $true
          }
          Write-Output "isAutomatedPR=$isAutomatedPR" >> $env:GITHUB_OUTPUT
          Write-Host "Is this Pull Request autogenerated $isAutomatedPR"
