name: Get Solution Name

on:
  workflow_call:
    outputs:
      solutionName:
        description: "Solution name for the current pr"
        value: ${{ jobs.currentPRSolutionName.outputs.sName }}

env:
  BRANCH_NAME: ${{ github.event.client_payload.pull_request.head.ref && github.event.client_payload.pull_request.head.ref || github.event.client_payload.pullRequestBranchName }}
  APP_INSIGHTS: ${{ vars.APPINSIGHTS }}
  RUN_ID: ${{ github.run_id }}
  PR_NUMBER: ${{ github.event.client_payload.pull_request.number && github.event.client_payload.pull_request.number || github.event.client_payload.pullRequestNumber }}

permissions:
  contents: read
  pull-requests: read

jobs:
  currentPRSolutionName:
    name: Generate output - Solution Name
    runs-on: ubuntu-latest
    outputs:
      sName: "${{ steps.getSolutionName.outputs.solutionName }}"
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 2
          ref: "${{ env.BRANCH_NAME }}"
      - name: Identify Solution
        shell: pwsh
        id: getSolutionName
        run: |
          $instrumentationKey = "${{ env.APP_INSIGHTS }}"
          $runId = "${{ env.RUN_ID }}"
          $pullRequestNumber = "${{ env.PR_NUMBER }}"
          Write-Host "pullRequestNumber $pullRequestNumber"
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module powershell-yaml
          ./.script/package-automation/getSolutionName.ps1 $runId $pullRequestNumber $instrumentationKey
