name: IssueComment

on: [issues]

jobs:
  commenting:
    runs-on: ubuntu-latest
    steps:
    - name: Generate a token
      id: generate_token
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      with:
        app_id: ${{ secrets.APPLICATION_ID }}
        private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

    - uses: actions/github-script@0.3.0
      env:
        APPTOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        github-token: ${{ env.APPTOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: 'Thank you for submitting an Issue to the Azure Sentinel GitHub repo! You should expect an initial response to your Issue from the team within 5 business days. Note that this response may be delayed during holiday periods. For urgent, production-affecting issues please raise a support ticket via the Azure Portal.' });
