name: On Demand Package using Slash Command
env:
    REPO_OWNER: "${{ vars.REPO_OWNER }}"
    REPO_NAME: "${{ vars.REPO_NAME }}"
    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
on:
  issue_comment:
    types: [created]

jobs:
  checkAutomatedPR:
    if: ${{ github.event.issue.pull_request && !github.event.pull_request.head.repo.fork && contains(github.event.comment.body, '/packaging') }}
    uses: ./.github/workflows/checkAutomatedPR.yaml

  pullRequestStatus:
    if: ${{ github.event.issue.pull_request && !github.event.pull_request.head.repo.fork && contains(github.event.comment.body, '/packaging') }}
    uses: ./.github/workflows/pullRequestStatus.yaml

  onDemandSlashCommandDispatch:
    runs-on: ubuntu-latest
    needs: [pullRequestStatus, checkAutomatedPR]
    if: ${{ needs.pullRequestStatus.outputs.isPullRequestMerged == 'False' && needs.checkAutomatedPR.outputs.isAutomatedPR == 'False' && contains(github.event.issue.labels.*.name, 'Content-Package') }}
    steps:
      - name: On Demand Packaging Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@67dfeb76529b35541a7c536976cba367cd2d364b
        with:
          token: ${{ env.GITHUB_TOKEN }}
          commands: package
          repository: ${{env.REPO_OWNER}}/${{env.REPO_NAME}}
          issue-type: pull-request
          reactions: false
