name: check that the version was updated

# Controls when the workflow will run
on:
  pull_request:
    paths:
       - 'detection**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  check-version-of-detection-was-updated:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # check out and run the script
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: bash .script/checkThatTemplatesVersionWasChanged.sh
